2025-04-07 04:23:02,414 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-04-07 04:23:02,415 - TournamentBot - INFO - Starting bot...
2025-04-07 04:23:02,416 - discord.client - INFO - logging in using static token
2025-04-07 04:23:02,853 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 2c4de70a6bf40dc3112729e9f0cd9877).
2025-04-07 04:23:04,999 - TournamentBot - INFO - Logged in as Team 3 - Tournament Bot#1540 (ID: 1334671496466927677)
2025-04-07 04:23:05,229 - TournamentBot - INFO - Synced 0 commands
2025-04-07 04:28:10,920 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-04-07 04:28:10,921 - TournamentBot - INFO - Starting bot...
2025-04-07 04:28:10,923 - discord.client - INFO - logging in using static token
2025-04-07 04:28:11,326 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 2c0a5cff8bcdb3126e61f925df3bf97c).
2025-04-07 04:28:13,363 - TournamentBot - INFO - Logged in as Team 3 - Tournament Bot#1540 (ID: 1334671496466927677)
2025-04-07 04:28:13,514 - TournamentBot - INFO - Synced 0 commands
2025-04-07 04:34:34,419 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-04-07 04:34:34,420 - TournamentBot - INFO - Starting bot...
2025-04-07 04:34:34,421 - discord.client - INFO - logging in using static token
2025-04-07 04:34:34,931 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: c1bbb12528ac2b3564884688eeed73f5).
2025-04-07 04:34:36,961 - TournamentBot - INFO - Logged in as Team 3 - Tournament Bot#1540 (ID: 1334671496466927677)
2025-04-07 04:34:37,128 - TournamentBot - INFO - Synced 0 commands
2025-04-07 04:36:06,167 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-04-07 04:36:06,168 - TournamentBot - INFO - Starting bot...
2025-04-07 04:36:06,168 - discord.client - INFO - logging in using static token
2025-04-07 04:36:07,246 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 5cdb54b7c313e08232a8a8b90c0626b9).
2025-04-07 04:36:09,255 - TournamentBot - INFO - Logged in as Team 3 - Tournament Bot#1540 (ID: 1334671496466927677)
2025-04-07 04:36:09,513 - TournamentBot - INFO - Synced 0 commands
2025-04-07 04:39:01,815 - discord.ui.view - ERROR - Ignoring exception in view <StartGameView timeout=None children=5> for item <Button style=<ButtonStyle.success: 3> url=None disabled=True label='Start\nGame' emoji=None row=1 sku_id=None>
Traceback (most recent call last):
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 430, in _scheduled_task
    await item.callback(interaction)
  File "C:\Coding Projects\TournamentBotKSU\Scripts\TournamentBot\ui\check_in.py", line 222, in start_game_button
    await game_state.initialize_games(games, cut_players, interaction.channel)
  File "C:\Coding Projects\TournamentBotKSU\Scripts\TournamentBot\game\game_state.py", line 105, in initialize_games
    blue_teams, red_teams = Matchmaking.matchmaking_multiple(players)
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Coding Projects\TournamentBotKSU\Scripts\Matchmaking.py", line 208, in matchmaking_multiple
    sorted_players = sorted(players, key=lambda p: p.tier)
  File "C:\Coding Projects\TournamentBotKSU\Scripts\Matchmaking.py", line 208, in <lambda>
    sorted_players = sorted(players, key=lambda p: p.tier)
                                                   ^^^^^^
AttributeError: 'dict' object has no attribute 'tier'
2025-04-07 04:50:54,949 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-04-07 04:50:54,950 - TournamentBot - INFO - Starting bot...
2025-04-07 04:50:54,951 - discord.client - INFO - logging in using static token
2025-04-07 04:50:55,484 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 18ade0cb4dbb2719fa970e7373d4518b).
2025-04-07 04:50:57,517 - TournamentBot - INFO - Logged in as Team 3 - Tournament Bot#1540 (ID: 1334671496466927677)
2025-04-07 04:50:57,671 - TournamentBot - INFO - Synced 0 commands
2025-04-07 04:54:20,633 - discord.ui.view - ERROR - Ignoring exception in view <GlobalControlView timeout=None children=1> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='Next Game / Re-Check-In' emoji=None row=None sku_id=None>
Traceback (most recent call last):
  File "c:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 430, in _scheduled_task
    await item.callback(interaction)
          ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 141, in __call__
    return self.callback(self.view, interaction, self.item)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GlobalControlView.next_game_callback() takes 2 positional arguments but 3 were given
2025-04-07 04:55:00,536 - discord.ui.view - ERROR - Ignoring exception in view <GlobalControlView timeout=None children=1> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='Next Game / Re-Check-In' emoji=None row=None sku_id=None>
Traceback (most recent call last):
  File "c:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 430, in _scheduled_task
    await item.callback(interaction)
          ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 141, in __call__
    return self.callback(self.view, interaction, self.item)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GlobalControlView.next_game_callback() takes 2 positional arguments but 3 were given
2025-04-07 04:55:18,715 - discord.ui.view - ERROR - Ignoring exception in view <GlobalControlView timeout=None children=1> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='Next Game / Re-Check-In' emoji=None row=None sku_id=None>
Traceback (most recent call last):
  File "c:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 430, in _scheduled_task
    await item.callback(interaction)
          ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 141, in __call__
    return self.callback(self.view, interaction, self.item)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GlobalControlView.next_game_callback() takes 2 positional arguments but 3 were given
2025-04-07 13:23:40,439 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-04-07 13:23:40,440 - TournamentBot - INFO - Starting bot...
2025-04-07 13:23:40,441 - discord.client - INFO - logging in using static token
2025-04-07 13:23:40,990 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: 79d77061dd4812dc5759df4f922fb34b).
2025-04-07 13:23:43,010 - TournamentBot - INFO - Logged in as Team 3 - Tournament Bot#1540 (ID: 1334671496466927677)
2025-04-07 13:23:43,234 - TournamentBot - INFO - Synced 0 commands
2025-04-07 13:26:02,236 - discord.ui.view - ERROR - Ignoring exception in view <GlobalControlView timeout=None children=1> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='Next Game / Re-Check-In' emoji=None row=None sku_id=None>
Traceback (most recent call last):
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 430, in _scheduled_task
    await item.callback(interaction)
          ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 141, in __call__
    return self.callback(self.view, interaction, self.item)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GlobalControlView.next_game_callback() takes 2 positional arguments but 3 were given
2025-04-07 13:26:15,929 - discord.ui.view - ERROR - Ignoring exception in view <GlobalSwapControlView timeout=None children=2> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=True label='Finalize Games' emoji=None row=0 sku_id=None>
Traceback (most recent call last):
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 430, in _scheduled_task
    await item.callback(interaction)
  File "C:\Coding Projects\TournamentBotKSU\Scripts\TournamentBot\ui\game_control.py", line 1038, in finalize_button
    await interaction.response.send_message(
    ...<2 lines>...
    )
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\interactions.py", line 855, in send_message
    await adapter.create_interaction_response(
    ...<6 lines>...
    )
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\webhook\async_.py", line 221, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
2025-04-07 13:26:26,177 - discord.ui.view - ERROR - Ignoring exception in view <GlobalControlView timeout=None children=1> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='Next Game / Re-Check-In' emoji=None row=None sku_id=None>
Traceback (most recent call last):
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 430, in _scheduled_task
    await item.callback(interaction)
          ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 141, in __call__
    return self.callback(self.view, interaction, self.item)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GlobalControlView.next_game_callback() takes 2 positional arguments but 3 were given
2025-04-07 13:42:22,445 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2025-04-07 13:42:22,447 - TournamentBot - INFO - Starting bot...
2025-04-07 13:42:22,447 - discord.client - INFO - logging in using static token
2025-04-07 13:42:22,989 - discord.gateway - INFO - Shard ID None has connected to Gateway (Session ID: b7f96bd2e4f2d88a8dd4ae8718e6e8c2).
2025-04-07 13:42:25,033 - TournamentBot - INFO - Logged in as Team 3 - Tournament Bot#1540 (ID: 1334671496466927677)
2025-04-07 13:42:25,246 - TournamentBot - INFO - Synced 0 commands
2025-04-07 13:45:46,757 - discord.ui.view - ERROR - Ignoring exception in view <GlobalControlView timeout=None children=1> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='Next Game / Re-Check-In' emoji=None row=None sku_id=None>
Traceback (most recent call last):
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 430, in _scheduled_task
    await item.callback(interaction)
          ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 141, in __call__
    return self.callback(self.view, interaction, self.item)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GlobalControlView.next_game_callback() takes 2 positional arguments but 3 were given
2025-04-07 13:45:56,543 - discord.ui.view - ERROR - Ignoring exception in view <GlobalControlView timeout=None children=1> for item <Button style=<ButtonStyle.primary: 1> url=None disabled=False label='Next Game / Re-Check-In' emoji=None row=None sku_id=None>
Traceback (most recent call last):
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 430, in _scheduled_task
    await item.callback(interaction)
          ~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 141, in __call__
    return self.callback(self.view, interaction, self.item)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GlobalControlView.next_game_callback() takes 2 positional arguments but 3 were given
2025-04-07 13:46:05,004 - discord.ui.view - ERROR - Ignoring exception in view <GameMVPControlView timeout=None children=1> for item <SkipMVPButton style=<ButtonStyle.secondary: 2> url=None disabled=False label='Skip MVP' emoji=None row=None sku_id=None>
Traceback (most recent call last):
  File "C:\Coding Projects\TournamentBotKSU\Scripts\TournamentBot\ui\game_control.py", line 233, in callback
    await interaction.response.send_message(embed=embed, ephemeral=True)
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\interactions.py", line 855, in send_message
    await adapter.create_interaction_response(
    ...<6 lines>...
    )
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\webhook\async_.py", line 221, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\ui\view.py", line 430, in _scheduled_task
    await item.callback(interaction)
  File "C:\Coding Projects\TournamentBotKSU\Scripts\TournamentBot\ui\game_control.py", line 262, in callback
    await interaction.response.send_message(embed=error_embed, ephemeral=True)
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\interactions.py", line 855, in send_message
    await adapter.create_interaction_response(
    ...<6 lines>...
    )
  File "C:\Coding Projects\TournamentBotKSU\.venv\Lib\site-packages\discord\webhook\async_.py", line 221, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
